In [1]:
import pandas as pd

excel_file_path = 'excels/Demanda-das-Empresas-por-Credito-Maio2024.xlsx'
credito_df = pd.read_excel(excel_file_path, sheet_name='Var. Mensal', skiprows=5, usecols='AC:AJ', header=None, index_col= None, names=['Industria', 'Comercio', 'Servicos', 'Demais', 'MPE', 'Medias', 'Grandes',	'Total'])

index_df = pd.read_excel(excel_file_path, sheet_name='Var. Mensal', skiprows=5, usecols='A', header=None)
index_series = index_df.iloc[:, 0]
credito_df.set_index(index_series, inplace=True)
credito_df.index = credito_df.index.astype(str)
credito_df.index.name = 'Data'

parquet_file_path = 'parquet/demanda_credito_cnpj.parquet'
credito_df.to_parquet(parquet_file_path, engine='pyarrow')
credito_df.head()

# Os dados aqui contidos possuem indicadores tanto por setor (Indústria,...,Demais) e por tamanho de empresa (MPE, Médias, Grandes). Isto será tratado posteriormente para manter uma entrada com os dados brutos.

,Industria,Comercio,Servicos,Demais,MPE,Medias,Grandes,Total
Data,,,,,,,,
2007-02-01,-0.044954,-0.086387,-0.073650,-0.020091,-0.079807,-0.020330,-0.004817,-0.076031
2007-03-01,0.127631,0.234692,0.161566,0.152155,0.203183,0.061056,0.010979,0.193491
2007-04-01,-0.067923,-0.125796,-0.060244,-0.089268,-0.099508,-0.024971,-0.002686,-0.095049
2007-05-01,0.047717,0.077441,0.030791,0.053539,0.058020,0.031727,0.003395,0.056169
2007-06-01,-0.042161,-0.045963,0.006704,0.010037,-0.026792,-0.009273,-0.003151,-0.025684

In [2]:
excel_file_path = 'excels/Atividade-do-Comercio-Maio2024.xlsx'
atividade_comercio_df = pd.read_excel(excel_file_path, sheet_name='Var. Mensal', skiprows=88, usecols='A:H', header=None, index_col= 0, names=['Data', 'Supermercados, Hipermercados, Alimentos e Bebidas',	'Moveis, Eletrodomesticos, Eletroeletronicos e Informatica', 'Combustiveis e Lubrificantes', 'Veiculos, Motos e Peças', 'Tecidos, Vestuário, Calçados e Acessorios', 'Material de Construcao', 'Geral'])

atividade_comercio_df.index = atividade_comercio_df.index.astype(str)
atividade_comercio_df.index.name = 'Data'

parquet_file_path = 'parquet/atividade_comercial.parquet'
atividade_comercio_df.to_parquet(parquet_file_path, engine='pyarrow')
atividade_comercio_df.head()

,"Supermercados, Hipermercados, Alimentos e Bebidas","Moveis, Eletrodomesticos, Eletroeletronicos e Informatica",Combustiveis e Lubrificantes,"Veiculos, Motos e Peças","Tecidos, Vestuário, Calçados e Acessorios",Material de Construcao,Geral
Data,,,,,,,
2007-02-01 00:00:00,0.010471,-0.011440,0.005723,-0.038458,-0.044334,-0.026735,-0.028000
2007-03-01 00:00:00,0.009217,0.019378,0.026546,0.086469,0.000451,0.020423,0.039392
2007-04-01 00:00:00,-0.008905,0.025440,-0.036499,-0.008936,-0.038652,-0.032599,-0.005324
2007-05-01 00:00:00,0.002098,0.005078,0.022278,0.049856,0.102764,0.034544,0.028577
2007-06-01 00:00:00,0.006212,0.022207,-0.024719,0.008092,-0.017293,0.009495,0.005273